version: 2
updates:
   # Maintain dependencies for npm
  - package-ecosystem: "npm"
    target-branch: "develop"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
