version: "3.9"

services:
    frontend:
        container_name: nginx
        build:
            context: .docker/development/nginx
        ports:
            - "8090:80"
        networks:
            - devhub

    frontend-node:
        container_name: node
        build:
            context: .docker/development/node
        volumes:
            - ./:/app
        tty: true
        networks:
            - devhub

networks:
    devhub:
        driver: bridge
