version: "3.9"

services:
    frontend-node:
        container_name: node
        build:
            context: .docker/development/node
        volumes:
            - ./:/app
        tty: true
        stdin_open: true
        ports:
            - "3000:3000"
        networks:
            - devhub

networks:
    devhub:
        driver: bridge
