name: Develop docker test
on: [ push, pull_request ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Cache frontend yarn
                uses: actions/cache@v2
                with:
                    path: node_modules
                    key: yarn-${{ hashFiles('yarn.lock') }}

            -   name: Docker pull
                run: make docker-pull

            -   name: Docker build
                run: make docker-build

            -   name: Docker up
                run: make docker-up

            -   name: Yarn install
                run: make yarn-install

            -   name: Yarn start dev
                run: docker-compose run --rm node yarn dev & npx wait-on http://localhost:3000
